### ISSUE TITLE
I got the wrong result. 

### ISSUE THREAD

**Issue by xiangjihan** [sschiau/Particle.php#5]
I use this library,and got all the $particleID num string like "2.5100994530733E+14".Is this the right result? The $particleID is it like "4611692470816737853"?

**Comment by sschiau** [comment]
**[const EPOCH](https://github.com/sschiau/Particle.php/blob/development/Particle.php#L34)** should be (13 digits) UNIX time in milliseconds (**1465343413213** = GMT: Tue, 07 Jun 2016 23:50:13.213 GMT).

**Comment by xiangjihan** [comment]
Yes，I use the 13digits Unix  time as the epoch.But it still abnormal.Is this duel to the 32 bit PHP parser?

**Comment by sschiau** [comment]
If your OS is 32bit... this won't work.
